# Assignment-3 — UCS420 Cognitive Computing
## Pandas

## Q1. Create the dataset

In [7]:
import pandas as pd
import numpy as np

# Dataset from the table given in the assignment
data = {
    "Td": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Refund": ["Yes", "No", "No", "Yes", "No", "No", "Yes", "No", "No", "No"],
    "Marital Status": ["Single", "Married", "Single", "Married", "Divorced",
                       "Married", "Divorced", "Single", "Married", "Single"],
    "Taxable Income": ["125K", "100K", "70K", "120K", "95K",
                       "60K", "220K", "85K", "75K", "90K"],
    "Cheat": ["No", "No", "No", "No", "Yes", "No", "No", "Yes", "No", "Yes"]
}

df = pd.DataFrame(data)
df

   Td Refund Marital Status Taxable Income Cheat
0   1    Yes         Single           125K    No
1   2     No        Married           100K    No
2   3     No         Single            70K    No
3   4    Yes        Married           120K    No
4   5     No       Divorced            95K   Yes
5   6     No        Married            60K    No
6   7    Yes       Divorced           220K    No
7   8     No         Single            85K   Yes
8   9     No        Married            75K    No
9  10     No         Single            90K   Yes

## Q2. Locate rows 0, 4, 7 and 8 using DataFrame

In [8]:
# iloc uses the DataFrame's integer positions
rows_0_4_7_8 = df.iloc[[0, 4, 7, 8]]
rows_0_4_7_8

   Td Refund Marital Status Taxable Income Cheat
0   1    Yes         Single           125K    No
4   5     No       Divorced            95K   Yes
7   8     No         Single            85K   Yes
8   9     No        Married            75K    No

## Q3. Navigate the DataFrame

1. Select rows from index **3 to 7**.
2. Select rows from index **4 to 8** and columns **2 to 4**.
3. Select all rows with column index **1 to 3**, including column index 3.

In [9]:
# 1. Select row from index 3 to 7 (inclusive)
df.iloc[3:8]

   Td Refund Marital Status Taxable Income Cheat
3   4    Yes        Married           120K    No
4   5     No       Divorced            95K   Yes
5   6     No        Married            60K    No
6   7    Yes       Divorced           220K    No
7   8     No         Single            85K   Yes

In [10]:
# 2. Select rows 4 to 8 and columns 2 to 4 (all inclusive)
df.iloc[4:9, 2:5]

  Marital Status Taxable Income Cheat
4       Divorced            95K   Yes
5        Married            60K    No
6       Divorced           220K    No
7         Single            85K   Yes
8        Married            75K    No

In [11]:
# 3. Select all rows with column index 1 to 3 (inclusive)
df.iloc[:, 1:4]

  Refund Marital Status Taxable Income
0    Yes         Single           125K
1     No        Married           100K
2     No         Single            70K
3    Yes        Married           120K
4     No       Divorced            95K
5     No        Married            60K
6    Yes       Divorced           220K
7     No         Single            85K
8     No        Married            75K
9     No         Single            90K

## Q4. Read the Iris CSV file and display its first five rows

In [12]:
# Make sure Iris.csv is in the same directory as this notebook.
iris_df = pd.read_csv("Iris.csv")

print("First five rows:")
display(iris_df.head())

First five rows:

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

## Q5. Delete row 4 and column 3 from the Iris DataFrame

In [13]:
# Delete row with index 4
iris_modified = iris_df.drop(index=4)

# Delete column with index 3
# iloc[:, 3] gives the column name at integer position 3.
column_3_name = iris_modified.columns[3]
iris_modified = iris_modified.drop(columns=column_3_name)

print(f"Deleted row index: 4")
print(f"Deleted column index: 3 ({column_3_name})")
display(iris_modified)

Deleted row index: 4
Deleted column index: 3 (PetalLengthCm)

      Id  SepalLengthCm  SepalWidthCm  PetalWidthCm         Species
0      1            5.1           3.5           0.2     Iris-setosa
1      2            4.9           3.0           0.2     Iris-setosa
2      3            4.7           3.2           0.2     Iris-setosa
3      4            4.6           3.1           0.2     Iris-setosa
5      6            5.4           3.9           0.4     Iris-setosa
..   ...            ...           ...           ...             ...
145  146            6.7           3.0           2.3  Iris-virginica
146  147            6.3           2.5           1.9  Iris-virginica
147  148            6.5           3.0           2.0  Iris-virginica
148  149            6.2           3.4           2.3  Iris-virginica
149  150            5.9           3.0           1.8  Iris-virginica

[149 rows x 5 columns]

## Q6. Create `employees.csv`

The employee data below is taken directly from the assignment table on page 2.

In [14]:
employees_data = {
    "Employee_ID": [101, 102, 103, 104, 105],
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Edward"],
    "Department": ["HR", "IT", "IT", "Marketing", "Sales"],
    "Age": [29, 34, 41, 28, 38],
    "Salary": [50000, 70000, 65000, 55000, 60000],
    "Years_of_Experience": [4, 8, 10, 3, 12],
    "Joining_Date": ["2020-03-15", "2017-07-19", "2013-06-01",
                     "2021-02-10", "2010-11-25"],
    "Gender": ["Female", "Male", "Male", "Female", "Male"],
    "Bonus": [5000, 7000, 6000, 4500, 5000],
    "Rating": [4.5, 4.0, 3.8, 4.7, 3.5]
}

employees = pd.DataFrame(employees_data)

# Save the sample dataset as requested
employees.to_csv("employees.csv", index=False)

display(employees)

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

### Q6(a). Shape of the DataFrame

In [15]:
print("Shape (rows, columns):", employees.shape)

Shape (rows, columns): (5, 10)

### Q6(b). Summary: data types and non-null counts

In [16]:
employees.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      str
 2   Department           5 non-null      str
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      str
 7   Gender               5 non-null      str
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), str(4)
memory usage: 532.0 bytes

### Q6(c). Descriptive statistics

In [17]:
employees.describe(include="all")

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
count,5.000000,5,5,5.000000,5.00000,5.000000,5,5,5.0,5.000000
unique,NaN,5,4,NaN,NaN,NaN,5,2,NaN,NaN
top,NaN,Alice,IT,NaN,NaN,NaN,2020-03-15,Male,NaN,NaN
freq,NaN,1,2,NaN,NaN,NaN,1,3,NaN,NaN
mean,103.000000,NaN,NaN,34.000000,60000.00000,7.400000,NaN,NaN,5500.0,4.100000
std,1.581139,NaN,NaN,5.612486,7905.69415,3.847077,NaN,NaN,1000.0,0.494975
min,101.000000,NaN,NaN,28.000000,50000.00000,3.000000,NaN,NaN,4500.0,3.500000
25%,102.000000,NaN,NaN,29.000000,55000.00000,4.000000,NaN,NaN,5000.0,3.800000
50%,103.000000,NaN,NaN,34.000000,60000.00000,8.000000,NaN,NaN,5000.0,4.000000
75%,104.000000,NaN,NaN,38.000000,65000.00000,10.000000,NaN,NaN,6000.0,4.500000
max,105.000000,NaN,NaN,41.000000,70000.00000,12.000000,NaN,NaN,7000.0,4.700000

### Q6(d). First 5 rows and last 3 rows

In [18]:
print("First 5 rows:")
display(employees.head(5))

print("Last 3 rows:")
display(employees.tail(3))

First 5 rows:

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

Last 3 rows:

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

### Q6(e). Calculate the required statistics

In [19]:
# i. Average salary
average_salary = employees["Salary"].mean()

# ii. Total bonus
total_bonus = employees["Bonus"].sum()

# iii. Youngest employee's age
youngest_age = employees["Age"].min()

# iv. Highest performance rating
highest_rating = employees["Rating"].max()

print("Average salary:", average_salary)
print("Total bonus paid:", total_bonus)
print("Youngest employee's age:", youngest_age)
print("Highest performance rating:", highest_rating)

Average salary: 60000.0
Total bonus paid: 27500
Youngest employee's age: 28
Highest performance rating: 4.7

### Q6(f). Sort by Salary in descending order

In [20]:
employees_sorted = employees.sort_values(by="Salary", ascending=False)
employees_sorted

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5

### Q6(g). Add a performance category

- **Excellent:** Rating >= 4.5
- **Good:** Rating >= 4.0 and < 4.5
- **Average:** Rating < 4.0

In [21]:
def performance_category(rating):
    if rating >= 4.5:
        return "Excellent"
    elif rating >= 4.0:
        return "Good"
    else:
        return "Average"

employees["Performance_Category"] = employees["Rating"].apply(performance_category)

employees[["Name", "Rating", "Performance_Category"]]

      Name  Rating Performance_Category
0    Alice     4.5            Excellent
1      Bob     4.0                 Good
2  Charlie     3.8              Average
3    Diana     4.7            Excellent
4   Edward     3.5              Average

### Q6(h). Identify missing values

In [22]:
missing_values = employees.isnull().sum()
missing_values

Employee_ID             0
Name                    0
Department              0
Age                     0
Salary                  0
Years_of_Experience     0
Joining_Date            0
Gender                  0
Bonus                   0
Rating                  0
Performance_Category    0
dtype: int64

### Q6(i). Rename `Employee_ID` to `ID`

In [23]:
employees.rename(columns={"Employee_ID": "ID"}, inplace=True)
employees

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

### Q6(j). Find employees who:
1. Have **more than 5 years of experience**.
2. Belong to the **IT department**.

In [24]:
# i. More than 5 years of experience
more_than_5_years = employees[employees["Years_of_Experience"] > 5]

print("Employees with more than 5 years of experience:")
display(more_than_5_years)

Employees with more than 5 years of experience:

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

In [25]:
# ii. Employees belonging to the IT department
it_employees = employees[employees["Department"] == "IT"]

print("Employees in the IT department:")
display(it_employees)

Employees in the IT department:

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average

### Q6(k). Add a `Tax` column that deducts 10% of Salary

In [26]:
# Tax = 10% of Salary
employees["Tax"] = employees["Salary"] * 0.10

# Salary after the 10% tax deduction
employees["Salary_After_Tax"] = employees["Salary"] - employees["Tax"]

employees

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category,Tax,Salary_After_Tax
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent,5000.0,45000.0
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good,7000.0,63000.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average,6500.0,58500.0
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent,5500.0,49500.0
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average,6000.0,54000.0

### Q6(l). Save the modified DataFrame to a new CSV file

In [27]:
output_file = "employees_modified.csv"
employees.to_csv(output_file, index=False)

print(f"Modified DataFrame saved as: {output_file}")
display(employees)

Modified DataFrame saved as: employees_modified.csv

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category,Tax,Salary_After_Tax
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent,5000.0,45000.0
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good,7000.0,63000.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average,6500.0,58500.0
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent,5500.0,49500.0
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average,6000.0,54000.0